version: '3.8'

services:
  web:
    image: myflaskapp:latest
    ports:
      - "80:5000"
    networks:
      - myflaskapp_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  myflaskapp_network:
    driver: overlay
